---
- hosts: nodes
  vars: 
    user1: farid
  tasks:
   - name: create a multiple user named {{ user1 }}
     user:
      name: "{{ user1 }}"
      state: present
     with_items:
       - Raj
       - Rahul
       - Ranveer  
   - name: install multiple packagees
     apt:
       name: "{{ item }}"
       state: present
     with_items:
       - gcc
       - nano
       - ntp
       - nginx
     
    
